name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write

env:
  DEVELOPER_DIR: /Applications/Xcode_15.3.app

jobs:
  ci:
    name: Run Build

    runs-on: macos-latest

    steps:
      # チェックアウト(GitHubリポジトリからソース取得)
      - uses: actions/checkout@v4

      # Xcodeの一覧出力
      - name: Show Xcode List
        run: ls /Applications | grep 'Xcode'

      # Xcodeのバージョン出力
      - name: Show Xcode Version
        run: xcodebuild -version

      # 使用可能Simulatorの一覧出力
      - name: Show Simulator List
        run: xcrun simctl list devices

      # Gemsのインストール
      - name: Install Bundled Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # Mintインストール
      - name: Install Mint
        run: |
          brew install mint

      # Gemsのキャッシュ
      - name: Cache Gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Mintで管理しているライブラリのキャッシュ
      - name: Cache Mint Packages
        uses: actions/cache@v4
        with:
          path: mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      # プロジェクトファイル設定
      - name: Setting Xcode Project
        run: |
          make setup

      # ビルド
      - name: Xcode Build
        run: set -o pipefail &&
          xcodebuild
          -workspace MMM.xcworkspace
          -sdk iphonesimulator
          -configuration Debug
          -scheme Debug
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
          -clonedSourcePackagesDirPath SourcePackages
          -derivedDataPath DerivedData
          build
          | bundle exec xcpretty

      # Danger実行
      - uses: MeilCli/danger-action@v6.0.3
        with:
          plugins_file: "Gemfile"
          install_path: "vendor/bundle"
          danger_file: "Danger/Buildfile"
          danger_id: "Build"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
