name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  DEVELOPER_DIR: /Applications/Xcode_15.3.app

jobs:
  ci:
    name: Run Test

    runs-on: macos-latest

    steps:
      # チェックアウト(GitHubリポジトリからソース取得)
      - uses: actions/checkout@v4

      # Xcodeの一覧出力
      - name: Show Xcode List
        run: ls /Applications | grep 'Xcode'

      # Xcodeのバージョン出力
      - name: Show Xcode Version
        run: xcodebuild -version

      # 使用可能Simulatorの一覧出力
      - name: Show Simulator List
        run: xcrun simctl list devices

      # Gemsのキャッシュ
      - name: Cache Gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Gemsのインストール
      - name: Install Bundled Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # Mintで管理しているライブラリのキャッシュ
      - name: Cache Mint Packages
        uses: actions/cache@v4
        with:
          path: mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      # Mintインストール
      - name: Install Mint
        run: |
          brew install mint

      # プロジェクトファイル生成
      - name: Generate Xcode Project
        run: |
          make setup

      # テスト(xcodebuild)
      - name: Xcode Test
        run: set -o pipefail &&
          xcodebuild
          -sdk iphonesimulator
          -configuration Debug
          -scheme MMM
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
          clean test
          | bundle exec xcpretty --report html
